"""Type stubs for fibonacci module."""

from __future__ import annotations

def fibonacci_python(n: int) -> int: ...

def fibonacci_python_iterative(n: int) -> int: ...

def benchmark(n: int = 35, runs: int = 5) -> None: ...

def benchmark_iterative(n: int = 35, runs: int = 5) -> None: ...
